############## style ##############
style:
  layout:
    max-width: 1130px #总体宽度
    post-max-width: 800px #文章内容宽度
  color:
    theme-main: "#1A98FF" # 主色调
    theme-secondary: "#DDF0FF" # 次色调
    text-main: "#333333" # 文字主色调
    text-secondary: "#898FA0" # 文字次色调
  animation:
    open: true # 如果开启动画的话会引入animation.css


########## 关于主页的设置 ##########
# home页可选类型
home:
  type: "home" # 主页的类型，可选 home | img | simple

# archive页可选类型
archive:
  type: "img" # archive的类型，可选 img | simple

categories:
  type: "img" # archive的类型，可选 img | simple

tags:
  type: "img" # archive的类型，可选 img | simple

newsroom:
  type: "img"

home_img_mode:
  default_cover:
    - https://raw.githubusercontent.com/CreatingServerW/Pic1/main/img/QQ%25E5%259B%25BE%25E7%2589%258720220416112142.png

archive_img_mode:
  default_cover: #默认的cover
    - https://mirror.ghproxy.com/https://raw.githubusercontent.com/CatalpaCute/image-hosting/main/CreatingBlog/binhai2022.jpg
# icon
icon: https://mirror.ghproxy.com/https://raw.githubusercontent.com/CatalpaCute/image-hosting/main/CreatingBlog/icon.png #标签页图标
#  header
site_name: Creating!
site_description: Create Your World! #The default meta description for all the meta descriptions
#Add description property to any page to change the meta description
menu:
  主页: /
  公告: /announcement
  NEWSROOM: /newsroom
  关于: /about


## 本地搜索
search:
  open: true # 是否开启
  page: /search # 页面路径（通常命名为search）



# 自我介绍
intro:
  title: Hi!欢迎来到Creating
  sub: '一个Minecraft服务器。 [悠日计划 维基百科](https://wiki.czzzz.work)' # markdown语法
  avator: https://cdn.jsdelivr.net/gh/fushaolei/img/20200524104925.jpg #头像 暂时还没用到
  author: CreatingOfficial #所有文章的默认作者

#联系方式
#更多图标：https://remixicon.com/
contact:
  Github:
    - http://github.com/teamCreating
    - ri-github-line
  #Email:
    #- mailto:1563250958@qq.com
    #- ri-mail-line
  bilibili:
    - https://space.bilibili.com/2018811423
    - ri-bilibili-line
  QQ:
    - https://jq.qq.com/?_wv=1027&k=ktXT2GAd
    - ri-chat-new-line

########## 关于文章的设置 ##########

# 文章toc索引栏设置
toc:
  open: true # 是否开启
  side: true  # 选择toc的位置，填true的话toc将会显示在文章的侧边，填false的话 toc将出现在文章的开头
  max: 2 #最大深度
  min: 2 #最小深度

# 插件
plugins:
  # 代码高亮，想要使用代码高亮，得先把根目录的_config.yml里的highlight的enable置成false
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/github.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles

# 评论系统设置
comments:
  open: false #是否开启评论系统
  system: gitalk #选择评论系统 可选 valine gitalk livere
  # Valine
  valine:
    appid: #Leancloud应用的AppID  这里和下面的要换成你自己的啊QAQ
    appkey: #Leancloud应用的AppKey
    verify: false #验证码
    notify: true #评论回复提醒
    avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
    #头像类型可见： https://valine.js.org/avatar.html
    placeholder: 留下你来过的痕迹~ #评论框占位符
  # Gitalk
  gitalk:
    owner:  #Github 用户名,
    repo:  #储存评论issue的github仓库名
    admin:  #Github 用户名
    clientID:  #`Github Application clientID`
    clientSecret: #`Github Application clientSecret`
  #livere
  livere: # 前往 http://livere.com/ 申请账号
    dataId: city #免费版本city
    dataUid: #安装代码中 data-uid 后面数据


pagination:
  prev: prev
  next: next

############## 其他 ##############

# 页脚
footer: Create Your World! Power by [Hexo](http://hexo.io/) Theme by [White](https://github.com/FuShaoLei/hexo-theme-white) # markdown语法

#有分类时是否开启menu分类页和自定义名字
menu_categories:
  open: true
  name: 分类

#可自定义归档标签页名字
archive_tab_name: Blog


#图片懒加载
lazyload:
  open: true #是否开启

# 安全设置
encrypt:
  # 启用插件
  enable: true
  # 自定义加密相关设置
  abstract: "这里的内容加密了，需要密码哦。"
  message: "请输入密码查看本文。"
  # 可以在这里设定特定标签对应的默认密码
  tags:
    - [name: "encryptAsSecret", password: "yoursecret"]
  # 错误消息设置
  wrong_pass_message: "密码错误，请重试。"
  wrong_hash_message: "内容认证失败，但仍可尝试查看。"
  # 是否禁用日志记录
  silent: false